
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test123
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: test123
    creationPolicy: Owner
  data:
    - secretKey: test123
      remoteRef:
        key: test123
        conversionStrategy: Unicode
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: strong-password
  namespace: external-secrets
spec:
  length: 128
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: external-secrets
spec:
  refreshInterval: 6h0m0s
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: azure-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password
  data:
    - match:
        secretKey: password # property in the generator output
        remoteRef:
          remoteKey: pushsecret-example
