---
# Generator for random string to be used for pushsecrets
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: strong-password
  namespace: external-secrets
spec:
  length: 128
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
# Use privileged namespace to push a secret
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-privileged
  namespace: external-secrets
spec:
  refreshInterval: 10m0s
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: azure-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password
  data:
    - match:
        secretKey: password # property in the generator output
        remoteRef:
          remoteKey: pushsecret-privileged
---
# Try to push a secret through an unprivileged namespace
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-unprivileged
  namespace: default
spec:
  refreshInterval: 10m0s
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: azure-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password
  data:
    - match:
        secretKey: password # property in the generator output
        remoteRef:
          remoteKey: pushsecret-unprivileged
---
# Pull secret into privileged namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-test-privileged
  namespace: external-secrets
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: es-test-privileged
    creationPolicy: Owner
  data:
    - secretKey: pushsecret-privileged
      remoteRef:
        key: pushsecret-privileged
---
# Pull secret into unprivileged namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-test-unprivileged
  namespace: default
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: es-test-unprivileged
    creationPolicy: Owner
  data:
    - secretKey: pushsecret-privileged
      remoteRef:
        key: pushsecret-privileged
